- name: Demo on variables
  hosts: all
  vars:
   URL: play.example.com
   Project: example
 # vars_prompt:
  #  - name: URL
  #   prompt: Enter URL
  #    private: no
 # vars_files:
 # - example-vars.yml
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
         URL: task.exmple.com
- name: Demo on vars
  hosts: all
  tasks:
    - name: Gather date
      shell: date +%F
      register: out

    - name: print date
      debug:
        msg: Date = {{ out.stdout }}

    - name: set a fact
      set_fact:
       Date: "{{out.stdout}}"

    - name: print Date
      debug:
        msg: Date ={{Date}}

    # Variable Precedence
    # 1.command line vars with -e
    # 2.Tasks
    # 3.vars_files
    # 4.vars_prompt
    # 5.vars
    #6. inventory vars