- name: Demo on filters
  hosts: all
  vars:
    URL: https://github.com/zelar-soft-roboshop/frontend/archive/main.zip
    tag_data:
      Environment: dev
      Application: payment
  tasks:
    - name: Print filename of a url
      debug:
        msg: "{{ URL | urlsplit }}