- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present
- name: Install npm
  apt:
    name: npm
    state: present
- name: Clean the old artifacts
  file:
     path: /var/www/html/{{COMPONENT}}
     state: absent
- name: Create the artifact path
  file:
    path: /var/www/html/{{COMPONENT}}
    state: directory
- name: Download frontend component
  get_url:
        url: http://172.31.212.18:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
        dest: /tmp
        username: admin
        password: admin123
- name: Unarchive a file that is already on the remote machine
  unarchive:
        src: /tmp/frontend-0.0.3.zip
        dest: /var/www/html/frontend
        remote_src: yes
- name: Change the path of root in sites-enabled
  ansible.builtin.replace:
    path: /etc/nginx/sites-enabled/default
    regexp: '/var/www/html'
    replace: '/var/www/html/frontend/dist'
  notify: Restart Nginx
- name: Start Nginx
  systemd:
      state: started
      name: nginx
      enabled: yes

- name: Change the Login and todo Ips
  ansible.builtin.replace:
    path: /etc/nginx/sites-enabled/default
    regexp: '/var/www/html'
    replace: '/var/www/html/fron

