- name: Download Artifacts from Nexus
  get_url:
    url: http://172.31.212.18:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp
    username: admin
    password: admin123
- name: Clean the old artifacts
  file:
    path: /root/{{COMPONENT}}
    state: absent
- name: Create the artifact path
  file:
    path: /root/{{COMPONENT}}
    state: directory

- name: Extract the {{COMPONENT}} Content
  unarchive:
    src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /root/{{COMPONENT}}
    remote_src: yes

