- name: Install go-lang
  apt:
    name: golang-go
    state: present
    update_cache: yes
- name: Download Artifacts from Nexus
  include_tasks: Download-artifacts-nexus.yml

- name: Setup SystemD Service
  include_tasks: systemd-setup.yml
