- name: Demo on loops
  hosts: all
  tasks:
    - name: print a list of fruits
      debug:
        msg: "Fruit = {{ item }}"
      loop:
        - banana
        - apple
        - orange
    - name: Count our fruit
      debug:
       msg: "{{ item }} with index {{ my_idx }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
       index_var: my_idx
    - name: Loop variable
      debug:
       msg: "Fruits = {{ myvar }}"
      loop:
         - apple
         - banana
         - pear
      loop_control:
       loop_var: myvar
    - name: print first value
             #when: ansible_loop.first
      debug:
        msg: "{{ ansible_loop.last }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
       extended: yes
    - name: Create servers
      debug:
       msg: "{{ item.name }}"
      loop:
       - name: server1
         disks: 3gb
         ram: 15Gb
         network:
           nic01: 100Gb
           nic02: 10Gb
       - name: server2
         disks: 3gb
         ram: 15Gb
         network:
           nic01: 100Gb
           nic02: 10Gb
      loop_control:
        label: "{{ item.name }}"
