- name: Demo on loops
  hosts: all
  tasks:
    - name: print a list of fruits
      debug:
        msg: "Fruit = {{ item }}"
      loop:
        - banana
        - apple
        - orange
    - name: Count our fruit
      debug:
       msg: "{{ item }} with index {{ my_idx }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
       index_var: my_idx
    - name: Loop variable
        debug:
          msg: "{{ myvar }}"
        loop:
          - apple
          - banana
          - pear
        loop_control:
          loop_var: myvar
