- name: Demo on filters
  hosts: all
  vars:
    URL: https://github.com/zelar-soft-roboshop/frontend/archive/main.zip
    tag_data:
      Environ: develop
      Applica: payme
  tasks:
    - name: Print filename of a url
      debug:
        msg: "{{ URL | urlsplit }}"
    - name: Print last column
      debug:
        msg: "{{ URL.split('/')}}"
    - name: Print last column
      debug:
        msg: "{{ URL.split('/') | first }}"

    - name: Print tag data
      debug:
        msg: "{{ tag_data | dict2items }}"
