- name: Install npm
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Download Artifacts from Nexus
  include_tasks: Download-artifacts-nexus.yml

- name: Setup SystemD Service
  include_tasks: systemd-setup.yml

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter
- name: Install Filebeat Monitoring
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: false
    IS_NODEJS: true
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }